name: SkyShop
main: io.github.pirgosth.skyshop.SkyShop
version: 1.0
api-version: 1.18
depend:
  - LibertyCore
  - Vault
softdepend: [ Multiverse-Core ]
command-complete: true
author: Pirgosth
commands:
  shop:
    description: Open Shop
    usage: /<command>
  shopadmin:
    description: Administration commands for shop management
    usage: /<command>
permissions:
  skyshop.command.reload:
    description: Allow reload command
    default: op
  skyshop.command.shop:
    description: Allow shop command
    default: op
  skyshop.command.*:
    description: Grant command wildcard permissions
    children:
      skyshop.command.reload: true
      skyshop.command.shop: true
  skyshop.admin.command.*:
    description: Grant admin command wildcard permissions
    default: op